//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hansa.Web.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Caption { get; set; }
        public string ToolTip { get; set; }
        public string Location { get; set; }
        public int ModuleID { get; set; }
        public int MenuOrder { get; set; }
    }
}
