//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hansa.Web.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetail
    {
        public int ID { get; set; }
        public string MenuID { get; set; }
        public int RoleCode { get; set; }
        public bool CanSelect { get; set; }
        public bool CanInsert { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanDelete { get; set; }
        public Nullable<bool> CanSend { get; set; }
        public Nullable<bool> CanCheck { get; set; }
        public Nullable<bool> CanApprove { get; set; }
        public bool CanPreview { get; set; }
        public bool AllChk { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
