//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hansa.Web.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string SecurityQuestion { get; set; }
        public string Answer { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EntryUserID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<short> ThanaID { get; set; }
        public Nullable<short> DivisionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CapchaCode { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string CompanyName { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> DefaultAllViwerForCommon { get; set; }
    }
}
